### ISSUE TITLE
Figure 3. Dynamics of R

### ISSUE THREAD

**Issue by OPA067** [Jiamian-Wang/T-MASS-text-video-retrieval#3]
Hello author, thank you for your excellent work. I would like to ask how Figure 3. Dynamics of R is drawn in the paper? Can you provide the code?

**Comment by Jiamian-Wang** [comment]
Hi there,

Thank you for your interest in this work! 

To plot the dynamics of R, you can 
* Firstly save the variable R of the testing data after each training epoch (e.g., using np.save), 
* Obtaining the data for plot, which should be a 5 x 1000 x 1000 x 512 array in the end (e.g., #epoch x #txt x #vid x dim, take MSRVTT-1K as an example).
* The remaining thing is to speciy a text idx. For a given text, plot 1000 curves (e.g., for loop), each curve correspond to 5 point of the L2-norm values (upon 512), that will result in the Fig.3 as shown in the manuscript. 

* We observe that, the R of the relevant pairs (diagnal values on 1000x1000), if can be correctly retrieved, in general is the smallest among all pairs. 

Unfortunately I cannot access to the local machine at present. I can provide the source code after the summer (e.g., late Aug). I hope this can help you. Please let me know if you have encounter any other issues.

**Comment by OPA067** [comment]
Thanks to the author for such a quick reply, my problem has been solved.
